# Generated by Django 5.0.6 on 2024-10-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_chat_seen_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedmessages',
            old_name='original_chat',
            new_name='original_message',
        ),
    ]
